@startuml

title "Dragon Native or Python Multiprocessing with Dragon"

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true

skinparam linetype ortho
' skinparam linetype polyline
' skinparam nodesep 30
' skinparam ranksep 20

[User program with Dragon Native] as UPN
[Python program with Multiprocessing\nand Dragon] as UPM
' [User Program in\nC/C++, FORTRAN, Python] as UPD
' [User Program \nwith Dragon Core] as UPDC
' [User Program \nwith Dragon Services] as UPDD
[Python Multiprocessing] as MP
UPM -d-> MP
' UPN -d-> MP

component "Dragon" {

    portin "Native API" as native_api

    [MPBridge] as DMPB
    [Native] as DNAT
    [GS Client] as DCLIENT
    [Infrastructure] as DINF
    [Core] as DCORE
    [Services] as DSERVICE

    DNAT <-- native_api

    DMPB --> native_api
    DNAT -d-> DCLIENT
    DNAT -d-> DCORE
    DCLIENT -l-> DINF
    DCLIENT --> DCORE
    DINF --> DCORE
    DSERVICE --> DINF
    DSERVICE --> DCORE
}

UPN --> native_api
MP -d-> DMPB

' UPDD -l-> client_api
' UPDD -l-> inf_api
' UPDD -l-> core_api
' UPDC -l-> core_api

'in case we want to hide components
hide $hidden
@enduml