@startuml

' title "Dragon MPBridge Architecture"

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true

skinparam linetype ortho
' skinparam linetype polyline
' skinparam nodesep 100
' skinparam ranksep 90

component "Services" as DSERV { 

    port "Infrastructure API" as ifport

    [Global Services] as GS
    [Local Services] as LS
    [Transport Agent] as TA
    [Launcher Backend] as LB

    GS <--> ifport
    LS <--> ifport
    LB <--> ifport
    TA <--> ifport
}

[GS Client] as DCLIENT

component "Dragon Infrastructure (C,Cython,Python)" as DINFRA {

    portin "Logging API " as log_api
    portin "Message API" as msg_api
    portin "Connection API" as conn_api
    portin "Infrastructure API" as inf_api
    portin "Utilities API" as util_api
    
    [Connection] as DCONN
    [Messages] as IMSG
    [Facts] as IFACTS
    [Parameters] as IPARAM
    [Util] as IUTIL
    [Infrastructure Descriptors] as IDESC
    [Logging] as ILOG

    IMSG <-u-> msg_api
    IMSG -d-> IDESC
    IFACTS <-u- inf_api
    IPARAM <-u- inf_api
    DCONN <-u- conn_api
    IUTIL <-u- util_api
    ILOG <-u- log_api
}

ifport --> inf_api 
ifport --> msg_api 
ifport --> conn_api 
ifport --> log_api 
ifport --> util_api


component "Dragon Core Libraries (C)" as DCORE {

    portin "Channel Set API" as dset_api
    portin "Channel API" as dchan_api
    portin "Managed Memory API" as dmm_api
    ' portin "Broadcast API" as dbcast_api
    ' portin "Gateway Message API" as dgmsg_api
    portin "Global Types API" as dtypes_api

    [Channel Set] as DSET
    [Channels] as DCHAN
    [Managed Memory] as DMEM
    ' [Broadcast] as DBROAD
    ' [Gateway Messages] as DGMSG
    [Common Types \n& Return Codes] as DTYPES

    DSET <-- dset_api
    DCHAN <-- dchan_api
    DMEM <-- dmm_api
    ' DBROAD <-- dbcast_api
    ' DGMSG <-- dgmsg_api
    DTYPES <-- dtypes_api
}

DCONN --d-> dchan_api
ILOG ---> dchan_api
ILOG ---> dmm_api
IPARAM ---> dtypes_api

' component "Runtime Services" as  DSERV {
    
'     [Global Services] as GS
'     [Local Services / Shepherd] as LS
'     [Launcher Backend] as LAB
'     [Transport] as TA
' }




'in case we want to hide components
hide $hidden
@enduml
