@startuml

' title "Round Robin Deployment"

skinparam componentStyle uml2
' skinparam shadowing false
' skinparam monochrome true

skinparam linetype ortho
' skinparam linetype polyline
' skinparam nodesep 30
skinparam ranksep 30

node "Login Node or Local Head Node" as LNode {

    component "Dragon Program" as UP {
        together { 
            component "Process object 1" as PO1 #lightgreen;line:black
            component "Process object 2" as PO2 #aliceblue;line:black
        }
        together {
            component "Process object 3" as PO3 #orange;line:black
            component "Process object 4" as PO4 #yellow;line:black
        }

        PO1 -[hidden]right- PO2
        PO2 -[hidden]right- PO3
        PO3 -[hidden]right- PO4
    }
}

node "Compute Node 1" as C1 {
    artifact "Process 1" as P1 #lightgreen 
    artifact "Process 4" as P4 #yellow
}

node "Compute Node 2" as C2 {
    artifact "Process 2" as P2 #aliceblue
}

node "Compute Node 3" as C3 {
    artifact "Process 3" as P3 #orange
}

PO1 --[#black]--> P1
PO2 -[#black]-> P2
PO3 -[#black]-> P3
PO4 --[#black]--> P4

@enduml