@startuml

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true
skinparam linetype polyline

node "Login / Head Node" as LNode {
    artifact "Launcher Frontend" as LF
    artifact "Overlay Frontend" as ONFE
}

node "Primary Compute Node" as PNode {

    artifact "Overlay Backend" as ONBE0
    artifact "Launcher Backend" as LB0
    artifact "Global Services" as GS
    artifact "Transport Service" as TS0
    together {
        artifact "Local Services" as LS0
        artifact "User Application" as APP0
    }
    artifact "Infrastructure Channels" as CH0
    artifact "User Channels" as UCH0
}

node "Compute Node" as CNode {

    artifact "Overlay Backend" as ONBE1
    artifact "Launcher Backend" as LB1
    artifact "Transport Service" as TS1
    together {
    artifact "Local Services" as LS1
    artifact "User Application" as APP1
    }
    artifact "Infrastructure Channels" as CH1
    artifact "User Channels" as UCH1
}

note as WLM
   Launched via Workload Manager
   from Launcher Frontend
end note

LF -- ONFE : channels
ONFE -down- ONBE0 : OverlayNet Tree
ONFE -down- ONBE1 : OverlayNet Tree
ONBE0 -- LB0 : channels
ONBE1 -- LB1 : channels

TS0 ---l--- TS1 : HPC Interconnect

LB1 -- LS1 : "stdin/stdout"
LB1 -- CH1
LS1 -- CH1
APP1 -- CH1
APP1 -- UCH1
APP1 -r-  LS1 : "stdin/stdout/stderr"
CH1 -d- TS1
UCH1 -d- TS1

LB0 -- LS0 : "stdin/stdout"
LB0 -- CH0
LS0 -- CH0
APP0 -- CH0
APP0 -- UCH0
APP0 -r-  LS0 : "stdin/stdout/stderr"
GS -- CH0
CH0 -d- TS0
UCH0 -d- TS0

WLM .. LB0
WLM .. LB1

@enduml