@startuml
skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true
skinparam linetype polyline

package "Global Services" {

    [Input Message Handler] as IMH
    [Command Processor] as CP
    [stdin Forwarder] as FWD
    [std* Monitor] as MON
    [Output Message Handler] as OUT
    [Death Watcher] as WATCH

    IMH --> CP
    IMH --> FWD
    FWD --> OUT
    CP --> MON
    OUT <-- MON
    WATCH -u-> OUT

}

[Linux Kernel] as K
interface "Linux Kernel API" as kernel_api

interface "Global Services Channel" as global_services_channel
interface "Shepherd Channel" as shepherd_channel
interface "Launcher Backend Channel" as launcher_backend_channel

K <-u- kernel_api

OUT --> launcher_backend_channel
OUT -d-> shepherd_channel
IMH <-u- global_services_channel
IMH --> kernel_api : halt event / normal halt
WATCH -d-> kernel_api : waitpid()


@enduml