@startuml
skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true
skinparam linetype polyline

package "Launcher on Single Node Deployment" {

        [Launcher Backend] as LB 
        [Launcher Frontend] as LF

        interface "stdout/stderr" as stdout
        interface "stdin"  as stdin

        LF -d-> stdin
        LF <-u- stdout
        LB <-d- stdin
        LB -u-> stdout 

}

interface "POSIX MQ" as posix_message_queue
interface "Launcher Channel" as launcher_channel
interface "Launcher Backend Channel" as bela_channel
interface "Shepherd Channel" as shepherd_channel
interface "Global Services Channel" as global_services_channel

LB <-r-> posix_message_queue
LB -d-> shepherd_channel
LB -d-> global_services_channel
LB <-u- bela_channel
LB <-u- launcher_channel

@enduml