@startuml

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true
skinparam linetype polyline

package "Launcher on Multi Node Deployment" {

    frame "Compute Node" {
        [Launcher Backend] as LB 
        [Network Backend] as NB
        [MRNet Server ??] as MS0
        
        interface "stdout/stderr" as stdout_be
        interface "stdin"  as stdin_be

        LB -down-> stdin_be
        NB <-up- stdin_be
        LB -down-> stdout_be
        NB -up-> stdout_be 
    }

    frame "Login Node" {
        [Launcher Frontend] as LF
        [Network Frontend] as NF

        interface "stdout/stderr" as stdout_fe
        interface "stdin"  as stdin_fe

        LF -down-> stdin_fe
        NF <-up- stdin_fe
        LF -down-> stdout_fe
        NF -up-> stdout_fe 
    }
}

    interface "MRNet" as mrnet

    NF <--> mrnet
    NB <--> mrnet

interface "POSIX MQ" as posix_message_queue
interface "Launcher Channel" as launcher_channel
interface "Launcher Backend Channel" as bela_channel
interface "Global Services Channel" as global_services_channel
interface "Shepherd Channel" as shepherd_channel 

LB <-u- launcher_channel
LB <-u- bela_channel
LB  -d-> global_services_channel
LB <-u-> posix_message_queue
LB -d-> shepherd_channel


@enduml