name: DragonHPC # will use GitHub repository name if not provided

icon: https://avatars.githubusercontent.com/u/138824827?s=200&v=4 # will use GitHub organization icon if not provided

headline: Accelerate distributed Python workflows # will use GitHub repository description if not provided

description: Dragon is a composable runtime that lets users create scalable, complex, and resilient HPC and AI applications and
  workflows through standard Python interfaces. Dragon provides capabilities to address many of the challenges around
  programmability, memory management, transparency, and efficiency on distributed systems. # will use GitHub repository description if not provided

language: Python # will attempt to fetch GitHub repository main language if not provided

release: # will attempt to fetch latest release from GitHub repository if not provided
  version: 0.13.1
  date: 2026-02-17 # format: YYYY-MM-DD
  url: https://pypi.org/project/dragonhpc/

documentation: # nothing will be used if not provided
  general: https://dragonhpc.github.io/dragon/doc/_build/html/index.html
  installation: https://dragonhpc.github.io/dragon/doc/_build/html/install.html
  tutorial: https://dragonhpc.github.io/dragon/doc/_build/html/start.html

execution_environment: # nothing will be used if not provided
  interfaces: # list of interfaces
    - Python API
    - C API
    - C++ API
  resource_managers: # list of supported resource managers
    - Slurm
    - PBSPro
    - Kubernetes
    - SSH
    - Linux
  transfer_protocols: # list of supported transfer protocols
    - TCP/IP
    - UCX
    - OFI
