INSTALL ?= install
INSTALL_DIR ?= ../dist/
INSTALL_MODE ?= 644

PRODUCT = dragon

build:
	@echo "Nothing to do for now"
	
clean:
	@echo "Nothing to do for now"

dist:
	$(INSTALL) -m $(INSTALL_MODE) -D $(PRODUCT) $(INSTALL_DIR)/lmod/$(PRODUCT)
