#!/bin/bash

# Set basic environment variables
DEVTOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
source ${DEVTOOLS_DIR}/VARIABLES

# Set up python environment using setup script
source ${DEVTOOLS_DIR}/setup "$@" "clean"

echo "Building source code."
if [[ "${UV_AVAILABLE}" == "1" ]]; then
    uv pip install -e src[dev,test,docs] --verbose
else
    python3 -m pip install -e src[dev,test,docs] --verbose
fi

