#!/bin/bash

# Set basic environment variables
HACK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
source ${HACK_DIR}/VARIABLES

ppath=`which python3`
env_str='_env'
if [[ "$ppath" != *"$env_str"* ]]; then
    echo "Activating environment."
    . _env/bin/activate
fi

echo "Building source code."
make -C src build
