#!/bin/bash

# Set basic environment variables
HACK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
source ${HACK_DIR}/VARIABLES

# Set up python environment using setup script
source ${HACK_DIR}/setup "$@" "clean"

echo "Building source code."
if [[ "${UV_AVAILABLE}" == "1" ]]; then
    uv pip install -e src
else
    python3 -m pip install -e src
fi

