#!/bin/bash

# Set basic environment variables
HACK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
source ${HACK_DIR}/VARIABLES

# Try deactivating any active environment. Move on if unable
cd $HACK_DIR/..
deactivate || true

# Make a clean virtual environment
python3 -m venv --clear _env
. _env/bin/activate
python3 -m pip install -U pip
python3 -m pip install -r src/requirements.txt


# Make a clean src directory
make -C src distclean

echo "Building source code."
make -C src build

# Run unit tests
# make -C test test
pushd test
python3 test_c_files.py -v -f || true
python3 test_channels.py -v -f || true
popd

# Build release
ls -alt src/dist || true
rm -fr src/dist && make -C src release

echo "BUILD COMPLETE"

# Tar up the built pkg

ls -alt src/release/
GITHASH="$(git rev-parse --short HEAD)"
GITBRANCH="$(git branch --show)"
PYTHON_VERSION=`python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}.{2}".format(*version))'`
PYTHON_MAJOR_VERSION=`python -c 'import sys; print(sys.version_info[0])'`
PYTHON_MINOR_VERSION=`python -c 'import sys; print(sys.version_info[1])'`
cp src/release/dragon-${DRAGON_VERSION}-${GITHASH}.tar.gz \
    src/release/dragon-${DRAGON_VERSION}-py${PYTHON_VERSION}-${GITHASH}.macos.tar.gz || true
