#!/bin/bash

HACK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
source ${HACK_DIR}/VARIABLES

env_str='_env'
if [ ! -d ${HACK_DIR}/${env_str} ]; then
    python3 -m venv _env;
fi

ppath=`which python3`

if [[ "$ppath" != *"$env_str"* ]]; then

    echo "Activating environment."
    . _env/bin/activate
fi
