#!/bin/bash

# Set basic environment variables that are set during a formal install
export DRAGON_VERSION=0.13.1
export DRAGON_BUILD_NTHREADS=6

HACK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
export DRAGON_BASE_DIR=${HACK_DIR}/../src
export DRAGON_INCLUDE_DIR=${DRAGON_BASE_DIR}/include
export DRAGON_LIB_DIR=${DRAGON_BASE_DIR}/lib

export PATH=${HACK_DIR}:${PATH}
export LD_LIBRARY_PATH=${DRAGON_BASE_DIR}/lib:${LD_LIBRARY_PATH}
# DYLD_FALLBACK_LIBRARY_PATH is for Mac OS X, but doesn't
# have any ill-effect in Linux
export DYLD_FALLBACK_LIBRARY_PATH=${DRAGON_BASE_DIR}/lib:${DYLD_FALLBACK_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=${DRAGON_BASE_DIR}/lib:${DYLD_LIBRARY_PATH}
export PYTHONPATH=${DRAGON_BASE_DIR}:${PYTHONPATH}



alias dragon-config="python3 -m dragon.cli dragon-config"