#!/usr/bin/env python3
import subprocess as sp
import sys
import os
from pathlib import Path

def main():
    executable = sys.argv[0]

    proc = sp.run(['ps', 'aux'], stdout=sp.PIPE, encoding='utf-8')

    path = os.path.abspath(executable)
    path = '/'.join((path.split('/')[:-1]))

    for line in proc.stdout.split('\n'):
        if 'python' in line and not executable in line:
            lst = line.split()
            pid = lst[1]
            print(f'*********************** Executing script.gdb on Process {pid} ***********************', flush=True)
            os.system(f'gdb -q -batch -x {path}/../hack/script.gdb -ex "getinfo {pid}"')
if __name__ == "__main__":
    main()
