@startuml

' title "Dragon Distributed Services"

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true

' skinparam linetype ortho
skinparam linetype polyline
' skinparam nodesep 10
' skinparam ranksep 20


package "Dragon Channel" as DC {
    [Managed Memory] as MM

    [Ordering Table Lock] as OTL
    [Ordering Table Queue] as OTQ

    [Usage Table Lock] as UTL
    [Usage Table Queue] as UTQ

    [Gateway Channel] as GWCHAN

    interface "Managed Memory API" as managed_memory_api
    interface "OT Lock API" as otlock_api
    interface "OT Queue API" as otqueue_api
    interface "UT Lock API" as utlock_api
    interface "UT Queue API" as utqueue_api

    MM <-d- managed_memory_api
    OTL <-d- otlock_api
    OTQ <-d- otqueue_api
    UTL <-d- utlock_api
    UTQ <-d- utqueue_api

    OTL -u-> managed_memory_api
    OTQ -u-> managed_memory_api
    UTL -u-> managed_memory_api
    UTQ -u-> managed_memory_api
}

interface "Dragon Channel API" as channel_api
interface "Gateway Channel API" as gw_channel_api

channel_api -u-> otlock_api
channel_api -u-> otqueue_api
channel_api -u-> utlock_api
channel_api -u-> utqueue_api

GWCHAN <--> gw_channel_api

@enduml