@startmindmap

* Front End
** Node 0
*** Node 32
**** 1056
**** ...
**** 1087
*** ...
**** ...
*** Node 63
**** Node 2048
**** ...
**** Node 2079
** ...
*** ...
**** ...
** Node 8
*** Node 288
**** Node 9248
**** ...
**** Node 9279
*** ...
**** ...
*** Node 311
**** Node 9984
**** ...
**** Node 9999
*** ...
*** Node 319
** ...
*** ...
** Node 31
*** Node 1024
*** ...
*** 1055

@endmindmap