apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragon-develop-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-file