apiVersion: v1
kind: Pod
metadata:
  name: build-dragon-pod
spec:
  restartPolicy: Never
  containers:
  - name: build-dragon
    image: mkalantzi/dragondev:latest
    resources:
      requests:
          memory: "4Gi"
      limits:
          memory: "8Gi"
    command: ["/bin/bash", "-c"]
    args:
    - |
      apt upgrade -y && apt update && \
      ucx_info -v && \
      echo "UCX is ready" && \
      cd dragon-develop/hpc-pe-dragon-dragon-k8s-merge-develop && \
      . hack/setup && \
      git config --global --add safe.directory /dragon-develop/hpc-pe-dragon-dragon-k8s-merge-develop/external/capnproto && \
      ldconfig -p | grep ucp && \
      # dragon-config -a "ucx-build-lib=/usr/lib/x86_64-linux-gnu/:ucx-runtime-lib=/usr/lib/x86_64-linux-gnu/:ucx-include=/usr/include" && \
      python3 -m dragon.cli dragon-config -a "ucx-build-lib=/usr/lib/x86_64-linux-gnu/:ucx-runtime-lib=/usr/lib/x86_64-linux-gnu/:ucx-include=/usr/include" && \
      . hack/clean_build && \
      ldd /dragon-develop/hpc-pe-dragon-dragon-k8s-merge-develop/src/lib/libdfabric_ucx.so
    volumeMounts:
    - mountPath: /dragon-develop
      name: dragon-develop-volume
  tolerations:
  - key: node-role.kubernetes.io/compute
    operator: Exists
    effect: NoExecute
  # - key: dragonhpc/compute
  #   operator: Exists
  #   effect: NoExecute
  volumes:
  - name: dragon-develop-volume
    persistentVolumeClaim:
      claimName: dragon-develop-pvc