apiVersion: v1
kind: Pod
metadata:
  name: management-pod
spec:
  containers:
  - name: management-container
    image: mkalantzi/dragondev:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      apt upgrade -y && apt update && \
      # cd dragon-develop && \
      # cd hpc-pe-dragon-dragon-k8s-merge-develop && \
      # . hack/setup && \
      sleep 1000000
    volumeMounts:
    - mountPath: /dragon-develop
      name: dragon-develop-volume1
  nodeSelector:
    kubernetes.io/hostname: svc-02
  volumes:
  - name: dragon-develop-volume1
    persistentVolumeClaim:
      claimName: dragon-develop-pvc
  restartPolicy: Never