import os
import sys
import argparse
import subprocess
from tempfile import NamedTemporaryFile

from .src import get_host_list
from .src.facts import ENV_DRAGON_RUN_NODE_FILE
from .src.common_args import add_common_args
from .src.exceptions import (
    DragonRunMissingAllocation,
    DragonRunNoSupportedWLM,
    DragonRunSingleNodeUnsupported,
)
from argparse import RawDescriptionHelpFormatter

DHOSTS_DESCRIPTION = """
The dhosts utility defines the list of hosts that should be used by other Dragon
runtime tools. To do this, dhosts generates a temporary hostfile and exports the
DRAGON_RUN_NODEFILE environment variable within a subshell. To generate the host
list, dhosts first attempts to detect an active Workload Manager (WLM)
allocation, such as from Slurm or PBS. If no WLM is present, or if dhosts is unable
to detect the allocated nodes from the WLM, the list of hosts can be specified
manually via the `--hostlist` or `--hostfile` options.

This is useful for running other dragon tools on a specific set of hosts without having to
specify the list of hosts to each tool individually. Since dhosts exports the
DRAGON_RUN_NODEFILE environment variable, any tool that relies on this environment variable
can automatically use the generated hostlist. For example, dragon-cleanup will automatically
use the hostlist generated by dhosts if DRAGON_RUN_NODEFILE is set in the environment.

To ensure efficiency across large multi-node environments, the DragonRun (drun) launcher
utilizes an SSH-tree to launch processes on each node. This requires that all nodes
are configured for password-less SSH and maintain mutual routability.

Example usage:

dhosts --hostlist host1,host2,host3
    Manually specify a list of hosts, in this case, host1, host2 and host3.

dhosts --hostfile my_hostfile.txt
    Specify a file containing a list of hosts, in this case, my_hostfile.txt.

dhosts --wlm slurm
    Force dhosts to look for an active Slurm allocation and use the nodes from that allocation.

dhosts --list
    Print the list of hosts that dhosts has determined should be used in the current environment.
"""

LIST_HELP="List known hosts in the current dragon run environment"

def get_parser():
    parser = argparse.ArgumentParser(
        prog="dhosts",
        description=DHOSTS_DESCRIPTION,
        formatter_class=RawDescriptionHelpFormatter,
    )
    add_common_args(parser, add_mode_group=False, add_ssh_args=False)

    parser.add_argument('--list', action="store_true", default=False, help=LIST_HELP)
    return parser


def get_args(args_input=None):
    parser = get_parser()
    args = parser.parse_args(args_input)
    return {key: value for key, value in vars(args).items() if value is not None}


def main():

    try:
        # Parse our arguments.
        args = get_args(sys.argv[1:])

        # Determine hostlist to use.
        host_list = get_host_list(**args)
        if not host_list:
            print(
                "Could not determine host(s) to use. Please specify --hostlist, --hostfile or ensure that you have an active slurm allocation.",
                file=sys.stderr,
                flush=True,
            )
            return 1

        if args["list"]:
            print("\n".join(host_list))
            return 0

        # Determine the user's default shell
        user_shell = os.environ.get("SHELL", "")
        if not user_shell:
            print(
                "Could not determine user shell. Please ensure that the SHELL environment variable is set",
                file=sys.stderr,
                flush=True,
            )
            return 1

        # Create temporary file. This will automatically be deleted.
        with NamedTemporaryFile(mode="w+t", suffix=".txt") as tmpfile:

            # Add environment variable pointing to the temporary file created above.
            env = os.environ.copy()
            env[ENV_DRAGON_RUN_NODE_FILE] = tmpfile.name
            tmpfile.write("\n".join(host_list))
            tmpfile.flush()

            try:
                return subprocess.run(
                    [user_shell],
                    shell=False,
                    env=env,
                    stdin=sys.stdin,
                    stdout=sys.stdout,
                    stderr=sys.stderr,
                ).returncode
            except Exception as exc:
                print("Error running subprocess: %s", exc, file=sys.stderr, flush=True)
                return 1

    except (DragonRunMissingAllocation, DragonRunNoSupportedWLM, DragonRunSingleNodeUnsupported) as exc:
        print(exc, flush=True)


if __name__ == "__main__":
    sys.exit(main())
