
@startuml

' title "Dragon Distributed Services"

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true

' skinparam linetype ortho
skinparam linetype polyline
' skinparam nodesep 10
' skinparam ranksep 20


package "Managed Memory" as MM {

    package "Pool" as PO {

        [Heap Manager] as HM
        [Bitsetter] as BS
        [Hex Dump] as HD
        [Scalable Lock] as LCK

        interface "Lock API" as lock_api

        HM --> BS
        HM --> HD
        HM --> lock_api
        LCK <-- lock_api

    }
    [Allocations] as AL
    [Request Handler] as RH

    interface "Memory Pool API" as pool_api
    interface "Memory Allocations API" as alloc_api
    interface "Memory Request API" as req_api 

    AL <-- alloc_api
    PO <-- pool_api
    AL --> pool_api
    RH <-- req_api
    RH --> pool_api
    RH --> alloc_api
}

interface "Managed Memory API" as managed_memory_api

alloc_api <-- managed_memory_api
pool_api <-- managed_memory_api
req_api <-- managed_memory_api

@enduml