@startuml

skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true

' skinparam linetype ortho
skinparam linetype polyline
' skinparam nodesep 10
' skinparam ranksep 20


package "Scalable Locks" as SL {
    [FIFO Lock] as FIFOLOCK
    [Greedy Lock] as GRLOCK
    [Readers Writer Lock] as RWLOCK

    interface "FIFO lock API" as fifo_api
    interface "Greedy lock API" as greedy_api
    interface "RWLock API " as rw_api

    FIFOLOCK <-- fifo_api
    GRLOCK <-- greedy_api
    RWLOCK <-- rw_api
}

interface "Scalable Locks API" as scalable_locks_api

fifo_api <-- scalable_locks_api
greedy_api <-- scalable_locks_api
rw_api <-- scalable_locks_api

@enduml
