{
 "title": "Dragon Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "deployment_name", "query": "opentsdb" }
  ]
 },
 "panels": [
  {
   "title": "CPU Metrics (telemetry_level=2)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "load_average"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "used_RAM"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "cpu_percent"
    }
   ]
  },
  {
   "title": "GPU Metrics (telemetry_level=3)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "gpu",
       "type": "wildcard"
      }
     ],
     "metric": "DeviceMemoryUtilization"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "gpu",
       "type": "wildcard"
      }
     ],
     "metric": "DeviceUtilization"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "gpu",
       "type": "wildcard"
      }
     ],
     "metric": "DevicePowerUsage"
    }
   ]
  },
  { "title": "Batch Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "num_running_tasks"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "num_completed_tasks"
    }
   ]
  },
  { "title": "telemetry_level = 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "db_size"
    }
   ]
  },
  {
   "title": "HSTA Metrics (telemetry_level=2)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request completion rate (requests/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 201 },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "source",
         "type": "wildcard"
        }
       ],
       "metric": "req_completion_rate"
      }
     ]
    },
    {
     "title": "Pending target channel operations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 201 },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "source",
         "type": "wildcard"
        }
       ],
       "metric": "pending_channel_operations"
      }
     ]
    },
    {
     "title": "Pending work requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 201 },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "source",
         "type": "wildcard"
        }
       ],
       "metric": "pending_work_requests"
      }
     ]
    },
    {
     "title": "Rendezvous bandwidth (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 211 },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "source",
         "type": "wildcard"
        }
       ],
       "metric": "rendezvous_bandwidth"
      }
     ]
    },
    {
     "title": "Target channel ops completion rate (ops/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 211 },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "source",
         "type": "wildcard"
        }
       ],
       "metric": "channel_operations_per_second"
      }
     ]
    }
   ]
  }
 ]
}