{
 "title": "Telemetry - Dragon",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Reboot Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reboot Nodes",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<form action=\"http://localhost:34383/api/reboot\" method=\"post\" target=\"hidden_if\">\n  <label for=\"hostnames\"> Enter hostnames (Comma Separated)</label>\n  <br>\n  <input style=\"width: 100%;\n  padding: 12px 20px;\n  margin: 8px 0;\n  display: inline-block;\n  border: 1px solid #ccc;\n  border-radius: 4px;\n  box-sizing: border-box;\" type=\"text\" id=\"hostnames\" name=\"hostnames\" placeholder=\"node_A,node_B,node_C\">\n  <br>\n  <label for=\"h_uids\"> Enter h_uids (Comma Separated)</label>\n  <br>\n  <input style=\"width: 100%;\n    padding: 12px 20px;\n    margin: 8px 0;\n    display: inline-block;\n    border: 1px solid #ccc;\n    border-radius: 4px;\n    box-sizing: border-box;\" type=\"text\" id=\"h_uids\" name=\"h_uids\" placeholder=\"node_A,node_B,node_C\">\n  <br>\n  <hr>\n  <button style=\"background-color: #04AA6D;\n    border: none;\n    color: white;\n    padding: 15px 32px;\n    text-align: center;\n    text-decoration: none;\n    display: inline-block;\n    font-size: 16px;\" type=\"submit\">Reboot</button>\n</form>\n<hr>\n<iframe name=\"hidden_if\" width=\"100%\" height=\"100\"></iframe>"
   },
   "targets": [
    { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "# Running Procs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "num_running_processes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "cpu_percent"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "used_RAM"
    }
   ]
  },
  { "title": "GPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "gpu",
       "type": "wildcard"
      }
     ],
     "metric": "DeviceMemoryUtilization"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "host",
       "type": "wildcard"
      },
      {
       "filter": "*",
       "groupBy": false,
       "tagk": "gpu",
       "type": "wildcard"
      }
     ],
     "metric": "DeviceUtilization"
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Inference Time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 14, "x": 0, "y": 51 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_0"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_1"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_2"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_3"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_4"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_5"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_6"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_7"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_8"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_9"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_10"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_11"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_12"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_13"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_14"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "key_time_15"
      }
     ]
    }
   ]
  }
 ]
}