{
 "title": "Dragon Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Start Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "pool_start_time"
      }
     ]
    },
    {
     "title": "Elapsed Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "puid",
         "type": "wildcard"
        }
       ],
       "metric": "elapsed_time"
      }
     ]
    },
    {
     "title": "Iteration Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "iteration_time"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "gpu",
         "type": "wildcard"
        }
       ],
       "metric": "DeviceMemoryUtilization"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "gpu",
         "type": "wildcard"
        }
       ],
       "metric": "DeviceUtilization"
      }
     ]
    },
    {
     "title": "Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        },
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "gpu",
         "type": "wildcard"
        }
       ],
       "metric": "DevicePowerUsage"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "load_average"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "load_average"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "used_RAM"
      }
     ]
    }
   ]
  },
  {
   "title": "telemetry_level = 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "*",
         "groupBy": false,
         "tagk": "host",
         "type": "wildcard"
        }
       ],
       "metric": "db_size"
      }
     ]
    }
   ]
  }
 ]
}