name: call-py312-runner-build

#
# Call runner-build.yaml for a python 3.12 dst-workflow or diy-workflow build
#

on:
  pull_request: # build for python 3.12 on all PRs
  push:
    branches: # build for python 3.12 ONLY on pushes to branches below
      - 'develop'
      - 'v0*branch' # catch release branches
      - 'main'

jobs:
  call-build:
    uses: ./.github/workflows/runner-build.yaml
    secrets: inherit
    with:
      build-command: "dst/dragon_build.sh -n -p 312" # dst example = "dst/dragon_build.sh -n -p 312" or diy example = "runBuildPrep.py312.sh"
      build-type: "use-hybrid-workflow" # options = use-dst-workflow use-hybrid-workflow use-diy-workflow
      build-container: "arti.hpc.amslabs.hpecorp.net/quay-remote/pypa/manylinux_2_28_x86_64"
      build-cpu: "x86" # options = "x86" or "arm"
